security:
    encoders:
        Raeting\UserBundle\Entity\User:
            algorithm: sha512
            iterations: 1000
            encode_as_base64: false
        # @TODO this should be removed, but still not working w/o it
        EstinaCMF\UserBundle\Entity\User:
            algorithm: sha512
            iterations: 1000
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        default_provider:
            entity: {class: RaetingUserBundle:User}
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false    
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: estinacmf_user.security.login
                check_path: estinacmf_user.security.login_check
            logout:
                path:   /logout
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/recover, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: ROLE_USER}
