analyst:
    pattern:  /
    defaults: { _controller: "RaetingRaetingBundle:Analyst:index" }

analyst_show:
    pattern:  /{id}/show
    defaults: { _controller: "RaetingRaetingBundle:Analyst:show" }

analyst_analysis:
    pattern:  /{id}/analysis
    defaults: { _controller: "RaetingRaetingBundle:Analyst:analysis" }
