analyst:
    pattern:  /
    defaults: { _controller: "RaetingRaetingBundle:Analyst:index" }

analyst_show:
    pattern:  /{id}/show
    defaults: { _controller: "RaetingRaetingBundle:Analyst:show" }
