analysis:
    pattern:  /
    defaults: { _controller: "RaetingRaetingBundle:Analyst:analysis" }
    
analysis_show:
    pattern:  /{ticker}
    defaults: { _controller: "RaetingRaetingBundle:Analyst:showticker" }