signals_create:
    pattern:  /create
    defaults: { _controller: "RaetingRaetingBundle:Signals:create" }
    requirements: { _method: post }
    
signals:
    pattern:  /
    defaults: { _controller: "RaetingRaetingBundle:Signals:index" }

signals_show:
    pattern:  /{uuid}
    defaults: { _controller: "RaetingRaetingBundle:Signals:show" }

signals_new:
    pattern:  /new
    defaults: { _controller: "RaetingRaetingBundle:Signals:new" }

