signals:
    pattern:  /
    defaults: { _controller: "RaetingRaetingBundle:Signals:index" }

signals_show:
    pattern:  /{id}/show
    defaults: { _controller: "RaetingRaetingBundle:Signals:show" }

signals_new:
    pattern:  /new
    defaults: { _controller: "RaetingRaetingBundle:Signals:new" }

signals_create:
    pattern:  /create
    defaults: { _controller: "RaetingRaetingBundle:Signals:create" }
    requirements: { _method: post }

signals_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RaetingRaetingBundle:Signals:edit" }

signals_update:
    pattern:  /{id}/update
    defaults: { _controller: "RaetingRaetingBundle:Signals:update" }
    requirements: { _method: post }

signals_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "RaetingRaetingBundle:Signals:delete" }
    requirements: { _method: get }
