signals_create:
    pattern:  /create
    defaults: { _controller: "RaetingRaetingBundle:Signals:create" }
    requirements: { _method: post }
    
signals:
    pattern:  /{page}
    defaults: { _controller: "RaetingRaetingBundle:Signals:index", page: 1 }

signals_show:
    pattern:  /{uid}/show
    defaults: { _controller: "RaetingRaetingBundle:Signals:show" }

signals_new:
    pattern:  /new
    defaults: { _controller: "RaetingRaetingBundle:Signals:new" }

signals_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RaetingRaetingBundle:Signals:edit" }

signals_update:
    pattern:  /{id}/update
    defaults: { _controller: "RaetingRaetingBundle:Signals:update" }
    requirements: { _method: post }
