raeting_signals:
    resource: "@RaetingRaetingBundle/Resources/config/routing/signals.yml"
    prefix:   /signals
    
raeting_analyst:
    resource: "@RaetingRaetingBundle/Resources/config/routing/analyst.yml"
    prefix:   /analysts

raeting_analysis:
    resource: "@RaetingRaetingBundle/Resources/config/routing/analysis.yml"
    prefix:   /recommendations
    
trader:
    resource: "@RaetingRaetingBundle/Resources/config/routing/trader.yml"
    prefix:   /traders
home:
    pattern:  /
    defaults: { _controller: "RaetingRaetingBundle:Raeting:index" }
    
api:
    pattern:  /api
    defaults: { _controller: "RaetingRaetingBundle:Raeting:api" }
    
ajax_symbols:
    pattern:  /ajaxsymbols
    defaults: { _controller: "RaetingRaetingBundle:Signals:ajaxGetAllSymbolsJson" }
    
my_signals:
    pattern:  /my_signals
    defaults: { _controller: "RaetingRaetingBundle:Signals:mysignals" }