raeting_raeting_signals:
    resource: "@RaetingRaetingBundle/Resources/config/routing/signals.yml"
    prefix:   /signals

home:
    pattern:  /
    defaults: { _controller: "RaetingRaetingBundle:Raeting:index" }
    
api:
    pattern:  /api
    defaults: { _controller: "RaetingRaetingBundle:Raeting:api" }