raeting_signals:
    resource: "@RaetingRaetingBundle/Resources/config/routing/signals.yml"
    prefix:   /signals

trader:
    resource: "@RaetingRaetingBundle/Resources/config/routing/trader.yml"
    prefix:   /traders
home:
    pattern:  /
    defaults: { _controller: "RaetingRaetingBundle:Raeting:index" }
    
api:
    pattern:  /api
    defaults: { _controller: "RaetingRaetingBundle:Raeting:api" }
ajax_symbols:
    pattern:  /ajaxsymbols
    defaults: { _controller: "RaetingRaetingBundle:Signals:ajaxGetAllSymbolsJson" }
    
pips:
    pattern:  /pips_calculator
    defaults: { _controller: "RaetingRaetingBundle:Profit:pips" }
my_signals:
    pattern:  /my_signals/{page}
    defaults: { _controller: "RaetingRaetingBundle:Signals:mysignals", page: 1 }