raeting_raeting_signals:
    resource: "@RaetingRaetingBundle/Resources/config/routing/signals.yml"
    prefix:   /signal

trader:
    resource: "@RaetingRaetingBundle/Resources/config/routing/trader.yml"
    prefix:   /trader
home:
    pattern:  /
    defaults: { _controller: "RaetingRaetingBundle:Raeting:index" }
    
api:
    pattern:  /api
    defaults: { _controller: "RaetingRaetingBundle:Raeting:api" }