services:
    raeting_raeting.form.type.extentity:
        class: Raeting\RaetingBundle\Form\Type\ExtEntityType
        arguments: 
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: extentity }
            
imports:
- { resource: services/signals.yml }
- { resource: services/market.yml }
- { resource: services/symbol.yml }
- { resource: services/currencyRate.yml }
- { resource: services/tickerRate.yml }
- { resource: services/analyst.yml }
- { resource: services/analysis.yml }
- { resource: services/fileManagement.yml }
- { resource: services/aggregation.yml }