parameters:
    raeting.helper.raeting.class: Raeting\RaetingBundle\Templating\Helper\RaetingHelper

services:
    raeting_raeting.form.type.extentity:
        class: Raeting\RaetingBundle\Form\Type\ExtEntityType
        arguments: 
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: extentity }
            
    raeting.raeting_helper:
        class: %raeting.helper.raeting.class%
        tags: [{ name: templating.helper, alias: 'raeting' }]
imports:
- { resource: services/signals.yml }
- { resource: services/market.yml }
- { resource: services/symbol.yml }
- { resource: services/rate.yml }
- { resource: services/analyst.yml }
- { resource: services/analysis.yml }
- { resource: services/fileManagement.yml }
- { resource: services/aggregation.yml }