api_signals:
    pattern:  /signals.{_format}
    defaults: { _controller: "RaetingApiBundle:Signal:index" }
    requirements:
      _format: json|xml
api_signals_show:
    pattern:  /signal/{id}.{_format}
    defaults: { _controller: "RaetingApiBundle:Signal:show" }
    requirements:
      _format: json|xml

api_traders:
    pattern:  /traders.{_format}
    defaults: { _controller: "RaetingApiBundle:Trader:index" }
    requirements:
      _format: json|xml

api_traders_show:
    pattern:  /trader/{id}.{_format}
    defaults: { _controller: "RaetingApiBundle:Trader:show" }
    requirements:
      _format: json|xml

