api_signals:
    pattern:  /signals.{_format}
    defaults: { _controller: "RaetingApiBundle:Signal:index" }
    requirements:
      _format: json|xml
      
api_signals_show:
    pattern:  /signals/{uuid}.{_format}
    defaults: { _controller: "RaetingApiBundle:Signal:show" }
    requirements:
      _format: json|xml

api_traders:
    pattern:  /traders.{_format}
    defaults: { _controller: "RaetingApiBundle:Trader:index" }
    requirements:
      _format: json|xml

api_traders_show:
    pattern:  /traders/{slug}.{_format}
    defaults: { _controller: "RaetingApiBundle:Trader:show" }
    requirements:
      _format: json|xml
      
api_trader_signals:
    pattern:  /traders/{slug}/signals.{_format}
    defaults: { _controller: "RaetingApiBundle:Trader:signals" }
    requirements:
      _format: json|xml

