parameters:
    raetingraeting.service.analyst.class: Raeting\RaetingBundle\Service\Analyst

services:
    raetingraeting.service.analyst:
        class: %raetingraeting.service.analyst.class%
        arguments: [@doctrine.orm.entity_manager, @raetingraeting.service.analysis, @raetingraeting.service.rate, @raetingraeting.service.dividend, @raeting.raeting_helper]