parameters:
    raetingraeting.service.currency_rate.class: Raeting\RaetingBundle\Service\CurrencyRate

services:
    raetingraeting.service.currency_rate:
        class: %raetingraeting.service.currency_rate.class%
        arguments: [@doctrine.orm.entity_manager, @raetingraeting.service.symbol]