Raeting\RaetingBundle\Entity\AnalystTotalReturn:
    type: entity
    table: analyst_total_return
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        value:
            type: decimal
            scale: 6
            nullable: false
    oneToOne:
        analyst:
            targetEntity: Analyst
            inversedBy: totalReturn
            joinColumns:
                analyst_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
