Raeting\RaetingBundle\Entity\Analyst:
    type: entity
    table: analyst
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        company:
            type: string
            length: 255
            fixed: false
        importSlug:
            type: string
            length: 255
            fixed: false
            column: import_slug
        slug:
            type: string
            length: 255
            fixed: false
            nullable: false
        rank:
            type: integer
            nullable: true
    oneToOne:
        totalReturn:
            targetEntity: AnalystTotalReturn
            mappedBy: analyst
    repositoryClass: Raeting\RaetingBundle\Entity\AnalystRepository
    lifecycleCallbacks: {  }
