Raeting\RaetingBundle\Entity\Benchmark:
    type: entity
    table: benchmark
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        value:
            type: decimal
            scale: 6
            nullable: false
    manyToOne:
        ticker:
            targetEntity: Symbol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticker_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
