Raeting\RaetingBundle\Entity\CurrencyRate:
    type: entity
    table: currency_rate
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        bid:
            type: decimal
            nullable: false
        ask:
            type: decimal
            nullable: false
        created:
            type: datetime
            nullable: false
        sourceTime:
            type: datetime
            nullable: false
            column: source_time
    manyToOne:
        currency:
            targetEntity: Symbol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                currency_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
