Raeting\RaetingBundle\Entity\Market:
    type: entity
    table: market
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 50
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
