Raeting\RaetingBundle\Entity\Rate:
    type: entity
    table: rate
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        bid:
            type: decimal
            nullable: false
        ask:
            type: decimal
            nullable: false
        high:
            type: decimal
            nullable: false
        low:
            type: decimal
            nullable: false
        created:
            type: datetime
            nullable: false
        sourceTime:
            type: datetime
            nullable: false
            column: source_time
        sourceDate:
            type: date
            nullable: false
            column: source_date
    manyToOne:
        symbol:
            targetEntity: Symbol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                symbol_id:
                    referencedColumnName: id
            orphanRemoval: false
    repositoryClass: Raeting\RaetingBundle\Entity\RateRepository
    lifecycleCallbacks: {  }
