Raeting\RaetingBundle\Entity\Signals:
    type: entity
    table: `signal`
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        uuid:
            type: string
            length: 13
            fixed: true
            nullable: false
        buy:
            type: boolean
            nullable: false
        open:
            type: decimal
            scale: 6
            nullable: false
        takeProfit:
            type: decimal
            scale: 6
            nullable: false
            column: take_profit
        stopLoss:
            type: decimal
            scale: 6
            nullable: false
            column: stop_loss
        profit:
            type: decimal
            scale: 6
            nullable: true
        pips:
            type: decimal
            scale: 6
            nullable: true
        description:
            type: string
            length: 255
            fixed: false
            nullable: false
        status:
            type: string
            values: [new,opened,closed,error]
            default: new
        created:
            type: datetime
            nullable: false
        opened:
            type: datetime
            nullable: false
        openExpire:
            type: datetime
            nullable: false
            column: open_expire
        closed:
            type: datetime
            nullable: false
        closeExpire:
            type: datetime
            nullable: false
            column: close_expire
    manyToOne:
        symbol:
            targetEntity: Raeting\RaetingBundle\Entity\Symbol
            cascade: {  }
            mappedBy: null
            orphanRemoval: false
        user:
            targetEntity: Raeting\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            orphanRemoval: false
    repositoryClass: Raeting\RaetingBundle\Entity\SignalsRepository
    lifecycleCallbacks: {  }
