Raeting\RaetingBundle\Entity\TotalReturn:
    type: entity
    table: total_return
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        value:
            type: decimal
            nullable: false
        updated:
            type: datetime
            nullable: false
    manyToOne:
        ticker:
            targetEntity: Symbol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticker_id:
                    referencedColumnName: id
            orphanRemoval: false
        analyst:
            targetEntity: Analyst
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                analyst_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
